services:
  postgres:
    image: postgres
    container_name: invsto
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "data"
    ports:
      - "5432:5432"
