"""Add unique constraint on datetime and instrument

Revision ID: c3d31108cd42
Revises: 560dfb1975f3
Create Date: 2025-01-19 16:21:07.612103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3d31108cd42"
down_revision: Union[str, None] = "560dfb1975f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_datetime_instrument", "xlsx_data", ["datetime", "instrument"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_datetime_instrument", "xlsx_data", type_="unique")
    # ### end Alembic commands ###
